Update Category.java
Added missing method from log4j Category class, which is quite useful and can be easily implemented.
(Found it when using library which called this method so I received NoSuchMethodError)